server:
  port: 8081
  ssl:
    key-alias: aliasoauthweb1
    key-password: 123456
    key-store: classpath:serverKeystore.jks
    key-store-password: 123456
#    key-store-provider: canOmit
#    key-store-type: canOmit
#    trust-store: classpath:clientside_cacerts
#    trust-store-password: 123456
#    trust-store-provider: canOmit
#    trust-store-type: canOmit
  tomcat:
    uri-encoding: UTF-8

# datasource
spring:
  datasource:
      url: jdbc:mysql://mysqlt1:3306/DPSBdbsso?characterEncoding=utf8
      username: user1
      password: aaa
  jpa:
    database: MYSQL
    show-sql: true
  ## Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

security:
  ignored: /favicon.ico,/scripts/**,/styles/**,/images/**
  sessions: ALWAYS
  oauth2:
      sso:
        loginPath: /login
      client:
        clientId: ssoclient
        clientSecret: ssosecret
        accessTokenUri: https://oauthlogin:8443/oauth/token
        userAuthorizationUri: https://oauthlogin:8443/oauth/authorize
        clientAuthenticationScheme: form
      resource:
        jwt:
          keyUri: https://oauthlogin:8443/oauth/token_key

securityconfig:
  logoutsuccssurl: /tosignout
  permitall: /rest/**,/bb**
  deniedpage: /deny
  urlroles: /**/new/** = admin;
            /**/edit/** = admin,editor;
            /**/delete/** = admin