server:
  port: 8083
  ssl:
    key-alias: aliasoauthres
    key-password: 123456
    key-store: classpath:serverKeystore.jks
    key-store-password: 123456
#    key-store-provider: canOmit
#    key-store-type: canOmit
#    trust-store: classpath:clientside_cacerts
#    trust-store-password: 123456
#    trust-store-provider: canOmit
#    trust-store-type: canOmit
  tomcat:
    uri-encoding: UTF-8
# datasource
spring:
  datasource:
      url: jdbc:mysql://mysqlt1:3306/DPSBdbsso?characterEncoding=utf8
      username: user1
      password: aaa
  jpa:
    database: MYSQL
    show-sql: true
  ## Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

security:
  oauth2:
    resource:
      jwt:
        keyUri: https://oauthlogin:8443/oauth/token_key
        # keyValue is from alias1_localhost1_rfc_cer_x509_pub. it seemed that the cer of jwt not verify hostname.
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjWx7waAGOW0GCvWtz22C0r2S9IDpjpURZiUbX9DFgUBSJ2/XqHYWP3I/I8IAWIvLqaE4RFAAwzaIySVN/pM2WUVRPCHlRF192HtrAc3CoZD5lVOHsU5f++22N6CrjQJQkX4V88efI596TbzqYkNJzmNLeBKuip9MLlMTW6z7+wuIw3KOUGk3+nH8MspMUk7vrGFOZG+UslkYCnx6+1gInEddaZm5HHyvAUh/lo7At3a2g7TaYE3PepSpZsZ6YNw68YhOkI+xG2OFkLek1vej8bGz6wEubeYI4nI3fjm8pEqh1s0NJrHwrxLtp9ncvo08bWEYYZonKJ5FvVw9+jgXiwIDAQAB
          -----END PUBLIC KEY-----
        # keyValue is from aliasoauthlogin_rfc_cer_x509_pub
#        keyValue: |
#          -----BEGIN PUBLIC KEY-----
#          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnYjlZs/cELCSP8n23dt9jaEGRih7w956LxF2Vadi0BSBcPIHmhXZV1TFvvDyggU20eyElqj64P5Uxg2/Y41rgxbK4T5U4eRP5JeZwrvVNig5N/7hmlhwRlsaR2Sdy2ZtUub7h9oEKLUOoS8f22DIhuf2R8kkpZ+zacwo17HUR5JqBa5vGU37wkpp3Vwj+VcIaNiGbcfaQJyWHJic99BzaIQFmkMNNkn9la7iaOWqVCJYwsZ4VUbxErshvdFonYIqKOL4lUxfugIUdmft32jUdKqP3j1Hlcbes9a483hSQAH2YmeazeVfZkv2CoQ5Jj6G8LRDli6M4v3J5dyyJ4rIuwIDAQAB
#          -----END PUBLIC KEY-----
